/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ResumenRouteImport } from './routes/resumen'
import { Route as MesMonthRouteImport } from './routes/mes.$month'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenRoute = ResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => rootRouteImport,
} as any)
const MesMonthRoute = MesMonthRouteImport.update({
  id: '/mes/$month',
  path: '/mes/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/resumen': typeof ResumenRoute
  '/mes/$month': typeof MesMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/resumen': typeof ResumenRoute
  '/mes/$month': typeof MesMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/buscar': typeof BuscarRoute
  '/resumen': typeof ResumenRoute
  '/mes/$month': typeof MesMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ajustes' | '/buscar' | '/resumen' | '/mes/$month'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/buscar' | '/resumen' | '/mes/$month'
  id: '__root__' | '/' | '/ajustes' | '/buscar' | '/resumen' | '/mes/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  BuscarRoute: typeof BuscarRoute
  ResumenRoute: typeof ResumenRoute
  MesMonthRoute: typeof MesMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumen': {
      id: '/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof ResumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes/$month': {
      id: '/mes/$month'
      path: '/mes/$month'
      fullPath: '/mes/$month'
      preLoaderRoute: typeof MesMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  BuscarRoute: BuscarRoute,
  ResumenRoute: ResumenRoute,
  MesMonthRoute: MesMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
